name = "people"
main = "src/worker.ts"
compatibility_date = "2023-08-14"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "people"
database_id = "64124d19-cb37-4d5f-91bd-a5c8812938d5"
